#!/usr/bin/env node
// Reproducible, editable presentation builder. Run with CODEX_PRIMARY_RUNTIME_NODE.
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL, fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
const ROOT=process.env.RESEARCH_MATERIALS_ROOT || path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const SKILL='/root/.codex/skills/builtins/presentations';
process.env.RUNTIME_NODE=process.env.CODEX_PRIMARY_RUNTIME_NODE;
process.env.RUNTIME_NODE_MODULES=process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES;
process.env.RUNTIME_PYTHON=process.env.CODEX_PRIMARY_RUNTIME_PYTHON;
process.env.RUNTIME_BIN_DIR=path.join(process.env.CODEX_PRIMARY_RUNTIME_ROOT,'dependencies/bin/override');
const {importRuntimeModule}=await import(pathToFileURL(path.join(SKILL,'container_tools/runtime_helpers.mjs')));
const {Presentation,PresentationFile}=await importRuntimeModule('@oai/artifact-tool');
const {FontLibrary,Canvas}=await import(pathToFileURL(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'@oai/artifact-tool/node_modules/skia-canvas/lib/index.js')));
const {finalizePresentation,makeNativeBulletParagraphs}=await import(pathToFileURL(path.join(SKILL,'container_tools/artifact_tool_utils.mjs')));
const F='Noto Sans';
const fontRoot=path.join(process.env.CODEX_PRIMARY_RUNTIME_ROOT,'dependencies/native/libreoffice-headless/libreoffice/share/fonts/truetype');
FontLibrary.use(F,['NotoSans-Regular.ttf','NotoSans-Bold.ttf','NotoSans-Italic.ttf'].map(f=>path.join(fontRoot,f)));
try { const {GlobalFonts}=await importRuntimeModule('@napi-rs/canvas'); for(const f of ['NotoSans-Regular.ttf','NotoSans-Bold.ttf','NotoSans-Italic.ttf']) GlobalFonts.registerFromPath(path.join(fontRoot,f)); } catch {}
const NAVY='#102A43', SLATE='#354F62', GRAY='#607D8B', LIGHT='#EDF3F5', WHITE='#FFFFFF';
const W=1280,H=720,M=70;
const ctx=new Canvas(4,4).getContext('2d');
const metrics=[];
function clean(s){return String(s??'').replace(/\*\*/g,'').replace(/[ \t]+/g,' ').trim();}
function linesFor(text,size,width,bold=false){ctx.font=`${bold?'bold ':''}${size}px "${F}"`;let lines=[]; for (let para of clean(text).split('\n')) {let l='';for(const word of para.split(/\s+/)){if(ctx.measureText((l?l+' ':'')+word).width>width&&l){lines.push(l);l=word;}else l+=(l?' ':'')+word;}lines.push(l);}return lines;}
function tx(slide,text,x,y,w,h,size=28,color=SLATE,bold=false,opts={}){text=clean(text);const sh=slide.shapes.add({geometry:'textbox',name:opts.name??text.slice(0,45),position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});sh.text=text;sh.text.style={typeface:F,fontSize:size,color,bold,autoFit:'none',wrap:'square',insets:{top:0,bottom:0,left:0,right:0},...opts};const lines=linesFor(text,size,w,bold);metrics.push({slide:slide.id,text,size,box:[x,y,w,h],estimatedLines:lines.length,estimatedHeight:lines.length*size*1.32});return sh;}
function bullets(slide,items,x,y,w,h,size=28,color=SLATE,after=14){if(!items?.length)return;const sh=tx(slide,'',x,y,w,h,size,color);sh.text=makeNativeBulletParagraphs(items.map(clean),{marginLeftPoints:19,hangingPoints:10,spaceAfterPoints:after});sh.text.style={typeface:F,fontSize:size,color,autoFit:'none',insets:{top:0,bottom:0,left:0,right:0}};metrics.push({slide:slide.id,bullets:items,size,box:[x,y,w,h],estimatedHeight:items.reduce((s,t)=>s+linesFor(t,size,w-30).length*size*1.32+19,0)});return sh;}
function footer(slide,doc,i,dark=false){tx(slide,doc.short_title,70,676,1075,25,16,dark?'#B8CCD8':GRAY);tx(slide,`${String(i+1).padStart(2,'0')} / 10`,1150,674,60,28,16,dark?'#B8CCD8':GRAY,false,{alignment:'right'});}
function title(slide,s,accent,dark=false){tx(slide,s.title,70,44,1140,118,44,dark?WHITE:NAVY,true); if(s.lead)tx(slide,s.lead,70,176,1140,90,29,dark?'#CDE5E6':accent,false);}
function table(slide,data,y,h=340){const values=[data.headers,...data.rows].map(r=>r.map(clean));const cols=data.headers.length;const width=1140;let raw=data.column_widths??data.columnWidths;let widths;
if(raw&&raw.length===cols){const sum=raw.reduce((a,b)=>a+b,0);widths=raw.map(v=>v/sum*width);}else {const lens=values[0].map((_,c)=>Math.max(...values.map(r=>(r[c]??'').length))); const weights=lens.map(x=>Math.min(2.7,Math.max(1,Math.sqrt(x)/3))); const sum=weights.reduce((a,b)=>a+b,0);widths=weights.map(v=>width*v/sum);}
const size=cols>=5?20:cols===4?22:values.length>=7?23:24;const heights=values.map((row,r)=>Math.max(r===0?50:values.length>=7?46:54,...row.map((c,i)=>linesFor(c,size,widths[i]-28,r===0).length*size*1.28+20)));const total=heights.reduce((a,b)=>a+b,0);if(total>h+20)console.warn('TABLE_DENSE',total,h,values);
const t=slide.tables.add({rows:values.length,columns:cols,left:70,top:y,width,height:total,columnWidths:widths,values});t.styleOptions={headerRow:true,bandedRows:false};t.borders.assign({fill:'#D5E0E6',width:0.7});for(let r=0;r<values.length;r++){t.rows[r].height=heights[r];for(let c=0;c<cols;c++){const cell=t.getCell(r,c);cell.fill=r===0?NAVY:(r%2?WHITE:'#F1F6F8');cell.text.style={typeface:F,fontSize:size,bold:r===0,color:r===0?WHITE:SLATE};}t.cells.block({row:r,column:0,rowCount:1,columnCount:cols}).assign({margins:{left:14,right:14,top:9,bottom:9},anchor:'ctr'});}return total;}
async function renderSlide(p,doc,s,i){const slide=p.slides.add();const accent=doc.accent||'#007F83';const dark=s.layout==='cover'||s.layout==='takeaway';slide.background.fill=dark?NAVY:WHITE;
if(s.layout==='cover') {const full=doc.title;const size=full.length>130?54:58;tx(slide,doc.category.toUpperCase(),70,68,1140,45,20,'#9DCFD0',true);tx(slide,full,70,165,1130,385,size,WHITE,true);if(doc.id==='icaif2026')tx(slide,'Original ten-page preprint edition',70,528,1140,35,22,'#B8CCD8');tx(slide,'Chorok Lee',70,585,1140,38,27,WHITE,true);tx(slide,'KAIST',70,626,1140,32,23,'#C0D2DC');}
else if(s.layout==='takeaway'){tx(slide,s.title,70,50,1140,100,44,WHITE,true);tx(slide,s.lead||doc.summary,70,185,1115,190,42,'#B8E2DF',true);bullets(slide,s.bullets,70,403,1120,208,27,WHITE);if(!s.bullets?.length&&s.columns) s.columns.forEach((c,j)=>tx(slide,`${c.heading}\n${c.body}`,70+j*575,408,535,200,25,WHITE));}
else {title(slide,s,accent);const start=s.lead?264:194;
if(s.layout==='table'&&s.table){const hh=table(slide,s.table,start,622-start);if(s.bullets?.length)bullets(slide,s.bullets,70,start+hh+18,1140,654-start-hh,23,SLATE,6);}
else if(s.layout==='comparison'&&s.columns?.length){const n=s.columns.length,gap=52,cw=(1140-gap*(n-1))/n,bs=n>2?24:28;let bodyBottom=0;s.columns.forEach((c,j)=>{const x=70+j*(cw+gap);tx(slide,c.heading,x,start,cw,70,n>2?28:32,accent,true);const bh=linesFor(c.body,bs,cw).length*bs*1.32+8;bodyBottom=Math.max(bodyBottom,start+80+bh);tx(slide,c.body,x,start+80,cw,bh,bs,SLATE);});if(s.bullets?.length){const by=Math.max(550,bodyBottom+12);bullets(slide,s.bullets,70,by,1140,655-by,23,SLATE,6);}}
else if(s.layout==='figure'&&s.figure?.path){const hasBullets=s.bullets?.length;const fy=s.lead?270:180;const fw=hasBullets?820:1140,fh=hasBullets?335:410;const data=await fs.readFile(path.isAbsolute(s.figure.path)?s.figure.path:path.join(ROOT,s.figure.path));slide.images.add({blob:new Uint8Array(data),contentType:'image/png',position:{left:70,top:fy,width:fw,height:fh},fit:'contain',alt:s.figure.caption||s.title});tx(slide,s.figure.caption,70,fy+fh+10,fw,45,18,GRAY);if(hasBullets)bullets(slide,s.bullets,935,fy+10,275,360,24);}
else if(s.layout==='equation'){const eq=s.equation_plain||s.equation||'';const es=eq.length>105?30:eq.length>75?35:43;tx(slide,eq,70,start+10,1140,130,es,accent,true);if(s.columns?.length){const cw=530;s.columns.forEach((c,j)=>{tx(slide,c.heading,70+j*595,start+165,cw,46,27,NAVY,true);tx(slide,c.body,70+j*595,start+225,cw,170,26,SLATE);});}else {const by=['aistats2027','regime-predictability'].includes(doc.id)?start+10+linesFor(eq,es,1140,true).length*es*1.32+(doc.id==='regime-predictability'?20:58):start+175;bullets(slide,s.bullets,70,by,1140,654-by,27,SLATE,['aistats2027','regime-predictability'].includes(doc.id)?11:14);}}
else {if(s.columns?.length){s.columns.forEach((c,j)=>{tx(slide,c.heading,70,start+j*145,350,48,29,accent,true);tx(slide,c.body,440,start+j*145,765,115,27,SLATE);});}else bullets(slide,s.bullets,70,start,1120,625-start,30);}}
if(i===9)tx(slide,'Source: github.com/'+doc.source.repository,70,632,1140,28,18,'#B8CCD8');
footer(slide,doc,i,dark);slide.speakerNotes.textFrame.setText(`${s.notes||''}\n\nSources\n${(s.sources?.length?s.sources:[doc.source.url]).join('\n')}\n${doc.source.version_note||''}`);return slide;}
async function build(id){metrics.length=0;const file=path.join(ROOT,'content',`${id}.json`);const doc=JSON.parse(await fs.readFile(file,'utf8'));if(doc.slides.length!==10)throw Error(`${id}: expected 10 slides`);const stamp=Date.now();const work=path.join(ROOT,'.deck-build',id,String(stamp));const qa=path.join(ROOT,'qa',id,'slides');const out=path.join(ROOT,'output',id);for(const d of [work,qa,out])await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(qa,'content-snapshot.json'),JSON.stringify(doc,null,2));const p=Presentation.create({slideSize:{width:W,height:H}});const slides=[];for(let i=0;i<10;i++)slides.push(await renderSlide(p,doc,doc.slides[i],i));const candidate=path.join(work,'candidate.pptx'),final=path.join(work,'slides_en.pptx');await(await PresentationFile.exportPptx(p)).save(candidate);const tables=doc.slides.map((s,i)=>s.layout==='table'&&s.table?i+1:null).filter(Boolean);await finalizePresentation({workspaceDir:ROOT,candidatePath:candidate,finalPath:final,pythonExecutable:process.env.CODEX_PRIMARY_RUNTIME_PYTHON,integrityValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...tables.flatMap(n=>['--require-native-table-slide',String(n)])],explicitTotalSlideCount:10,requiredNativeTableOwnerSlides:tables,fontPolicy:{basis:'design',families:[F]},verifyArtifactToolImport:true,receiptPath:path.join(qa,`validation-${stamp}.json`)});await fs.copyFile(final,path.join(out,'slides_en.pptx'));await fs.copyFile(path.join(qa,`validation-${stamp}.json`),path.join(qa,'validation.json'));
for(let i=0;i<10;i++){const png=await p.export({slide:slides[i],format:'png',scale:1.4});await fs.writeFile(path.join(qa,`slide-${i+1}.png`),new Uint8Array(await png.arrayBuffer()));const layout=await slides[i].export({format:'layout'});await fs.writeFile(path.join(qa,`slide-${i+1}.layout.json`),await layout.text());}
await fs.writeFile(path.join(qa,'content-metrics.json'),JSON.stringify(metrics,null,2));
const soffice=path.join(process.env.CODEX_PRIMARY_RUNTIME_ROOT,'dependencies/bin/override/soffice');const conv=spawnSync(soffice,['--headless',`-env:UserInstallation=file://${path.join(work,'lo-profile')}`,'--convert-to','pdf','--outdir',work,final],{encoding:'utf8',timeout:120000});if(conv.status!==0)throw Error(`PDF conversion failed ${conv.stderr}`);await fs.copyFile(path.join(work,'slides_en.pdf'),path.join(out,'slides_en.pdf'));console.log(JSON.stringify({id,pptx:path.join(out,'slides_en.pptx'),pdf:path.join(out,'slides_en.pdf'),qa}));}
const ids=process.argv.slice(2);if(!ids.length)throw Error('Provide paper IDs');for(const id of ids)await build(id);
